import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import '../models/flow_models.dart';

class ConversationExportService {
  static Future<void> exportToPDF({
    required List<BuddyMessage> messages,
    required BuildContext context,
    String? conversationTitle,
  }) async {
    try {
      final pdf = pw.Document();
      final title = conversationTitle ?? 'Buddy AI Conversation';
      final exportDate = DateFormat('yyyy-MM-dd HH:mm').format(DateTime.now());

      // Create PDF content
      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(32),
          build: (pw.Context context) {
            return [
              // Header
              pw.Header(
                level: 0,
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      title,
                      style: pw.TextStyle(
                        fontSize: 24,
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColors.blue800,
                      ),
                    ),
                    pw.SizedBox(height: 8),
                    pw.Text(
                      'Exported on $exportDate',
                      style: pw.TextStyle(
                        fontSize: 12,
                        color: PdfColors.grey600,
                      ),
                    ),
                    pw.Divider(color: PdfColors.grey300),
                    pw.SizedBox(height: 16),
                  ],
                ),
              ),

              // Messages
              ...messages.map((message) => _buildMessageWidget(message)),

              // Footer
              pw.SizedBox(height: 20),
              pw.Divider(color: PdfColors.grey300),
              pw.Text(
                'Generated by Buddy AI • ${messages.length} messages',
                style: pw.TextStyle(fontSize: 10, color: PdfColors.grey500),
                textAlign: pw.TextAlign.center,
              ),
            ];
          },
        ),
      );

      // Save and share PDF
      await _savePDF(pdf, title, context);
    } catch (e) {
      _showErrorSnackBar(context, 'Failed to export conversation: $e');
    }
  }

  static pw.Widget _buildMessageWidget(BuddyMessage message) {
    final isUser = message.role == BuddyRole.user;
    final timestamp = DateFormat('HH:mm').format(message.timestamp);

    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 16),
      child: pw.Column(
        crossAxisAlignment: isUser
            ? pw.CrossAxisAlignment.end
            : pw.CrossAxisAlignment.start,
        children: [
          // Message header
          pw.Row(
            mainAxisAlignment: isUser
                ? pw.MainAxisAlignment.end
                : pw.MainAxisAlignment.start,
            children: [
              if (!isUser) ...[
                pw.Container(
                  width: 24,
                  height: 24,
                  decoration: pw.BoxDecoration(
                    color: PdfColors.blue500,
                    borderRadius: pw.BorderRadius.circular(12),
                  ),
                  child: pw.Center(
                    child: pw.Text(
                      'AI',
                      style: pw.TextStyle(
                        color: PdfColors.white,
                        fontSize: 10,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                  ),
                ),
                pw.SizedBox(width: 8),
                pw.Text(
                  'Buddy AI',
                  style: pw.TextStyle(
                    fontSize: 12,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.blue800,
                  ),
                ),
              ] else ...[
                pw.Text(
                  'You',
                  style: pw.TextStyle(
                    fontSize: 12,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.green800,
                  ),
                ),
                pw.SizedBox(width: 8),
                pw.Container(
                  width: 24,
                  height: 24,
                  decoration: pw.BoxDecoration(
                    color: PdfColors.green500,
                    borderRadius: pw.BorderRadius.circular(12),
                  ),
                  child: pw.Center(
                    child: pw.Text(
                      'U',
                      style: pw.TextStyle(
                        color: PdfColors.white,
                        fontSize: 10,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                  ),
                ),
              ],
              pw.SizedBox(width: 8),
              pw.Text(
                timestamp,
                style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
              ),
            ],
          ),

          pw.SizedBox(height: 8),

          // Message content
          pw.Container(
            padding: const pw.EdgeInsets.all(12),
            decoration: pw.BoxDecoration(
              color: isUser ? PdfColors.blue50 : PdfColors.grey100,
              borderRadius: pw.BorderRadius.circular(12),
              border: pw.Border.all(
                color: isUser ? PdfColors.blue200 : PdfColors.grey300,
                width: 1,
              ),
            ),
            constraints: const pw.BoxConstraints(maxWidth: 400),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [_buildMessageContent(message.content)],
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildMessageContent(String content) {
    // Handle code blocks
    if (content.contains('```')) {
      return _buildCodeBlockContent(content);
    }

    // Handle regular text
    return pw.Text(
      content,
      style: pw.TextStyle(
        fontSize: 11,
        lineSpacing: 1.4,
        color: PdfColors.black,
      ),
    );
  }

  static pw.Widget _buildCodeBlockContent(String content) {
    final parts = content.split('```');
    final widgets = <pw.Widget>[];

    for (int i = 0; i < parts.length; i++) {
      if (i % 2 == 0) {
        // Regular text
        if (parts[i].trim().isNotEmpty) {
          widgets.add(
            pw.Text(
              parts[i].trim(),
              style: pw.TextStyle(
                fontSize: 11,
                lineSpacing: 1.4,
                color: PdfColors.black,
              ),
            ),
          );
          widgets.add(pw.SizedBox(height: 8));
        }
      } else {
        // Code block
        final lines = parts[i].split('\n');
        final language = lines.isNotEmpty ? lines.first.trim() : '';
        final code = lines.skip(1).join('\n').trim();

        widgets.add(
          pw.Container(
            padding: const pw.EdgeInsets.all(12),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey900,
              borderRadius: pw.BorderRadius.circular(6),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                if (language.isNotEmpty) ...[
                  pw.Text(
                    language,
                    style: pw.TextStyle(
                      fontSize: 10,
                      color: PdfColors.grey400,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                  pw.SizedBox(height: 4),
                ],
                pw.Text(
                  code,
                  style: pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.white,
                    fontWeight: pw.FontWeight.normal,
                  ),
                ),
              ],
            ),
          ),
        );
        widgets.add(pw.SizedBox(height: 8));
      }
    }

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: widgets,
    );
  }

  static Future<void> _savePDF(
    pw.Document pdf,
    String fileName,
    BuildContext context,
  ) async {
    try {
      // Generate PDF bytes
      final Uint8List bytes = await pdf.save();

      // Try to save to Downloads folder
      try {
        final directory = await getDownloadsDirectory();
        if (directory != null) {
          final cleanFileName = fileName
              .replaceAll(RegExp(r'[^\w\s-]'), '')
              .trim();
          final timestamp = DateFormat(
            'yyyyMMdd_HHmmss',
          ).format(DateTime.now());
          final file = File(
            '${directory.path}/${cleanFileName}_$timestamp.pdf',
          );

          await file.writeAsBytes(bytes);

          _showSuccessSnackBar(context, 'PDF saved to Downloads: ${file.path}');
          return;
        }
      } catch (e) {
        print('Failed to save to Downloads: $e');
      }

      // Fallback: Use printing package to share
      await Printing.sharePdf(
        bytes: bytes,
        filename:
            '${fileName}_${DateFormat('yyyyMMdd_HHmmss').format(DateTime.now())}.pdf',
      );

      _showSuccessSnackBar(context, 'PDF ready to share');
    } catch (e) {
      _showErrorSnackBar(context, 'Failed to save PDF: $e');
    }
  }

  static void _showSuccessSnackBar(BuildContext context, String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: Colors.green,
        duration: const Duration(seconds: 3),
        behavior: SnackBarBehavior.floating,
      ),
    );
  }

  static void _showErrorSnackBar(BuildContext context, String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: Colors.red,
        duration: const Duration(seconds: 3),
        behavior: SnackBarBehavior.floating,
      ),
    );
  }

  static Future<void> exportConversationToPDF({
    required List<BuddyMessage> messages,
    required BuildContext context,
    String? title,
  }) async {
    if (messages.isEmpty) {
      _showErrorSnackBar(context, 'No messages to export');
      return;
    }

    await exportToPDF(
      messages: messages,
      context: context,
      conversationTitle: title ?? 'Buddy AI Conversation',
    );
  }
}
